import jsPDF from 'jspdf';

export default function DownloadReport({ analysis }) {
  const generateTextReport = () => {
    const report = `VERITY FORENSIC ANALYSIS REPORT
Generated: ${new Date().toLocaleString()}

========================================
REASONING PROCESS 
========================================

${analysis.thinking}

========================================
VERIFIED TIMELINE
========================================

${analysis.timeline.map((event, i) => `
${i + 1}. ${event.datetime}
   Event: ${event.event}
   Sources: ${event.sources.join(', ')}
   Confidence: ${event.confidence.toUpperCase()}
   ${event.reasoning ? `Reasoning: ${event.reasoning}` : ''}
`).join('\n')}

========================================
CONTRADICTIONS DETECTED
========================================

${analysis.contradictions.length === 0 ? 'No contradictions found.' : analysis.contradictions.map((c, i) => `
Contradiction ${i + 1}: ${c.severity.toUpperCase()}
ID: ${c.id}
Confidence: ${(c.confidence * 100).toFixed(0)}%

Claim A: ${c.claim_a.statement}
Source: ${c.claim_a.source}
Credibility: ${c.claim_a.credibility.toUpperCase()}

Claim B: ${c.claim_b.statement}
Source: ${c.claim_b.source}
Credibility: ${c.claim_b.credibility.toUpperCase()}

Analysis: ${c.analysis}

Verdict: ${c.verdict}
`).join('\n')}

========================================
SUMMARY
========================================

${analysis.summary || 'No summary available.'}

========================================
END OF REPORT
========================================

This report was generated by Verity - Forensic Truth Verification Engine
`;

    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `verity-analysis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generatePDFReport = () => {
    const doc = new jsPDF();
    let yPos = 20;
    const margin = 20;
    const pageWidth = doc.internal.pageSize.getWidth();
    const maxWidth = pageWidth - (margin * 2);

    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('VERITY FORENSIC ANALYSIS REPORT', margin, yPos);
    yPos += 10;

    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    doc.text(`Generated: ${new Date().toLocaleString()}`, margin, yPos);
    yPos += 15;

    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('REASONING PROCESS', margin, yPos);
    yPos += 7;

    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    const thinkingLines = doc.splitTextToSize(analysis.thinking, maxWidth);
    thinkingLines.forEach(line => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.text(line, margin, yPos);
      yPos += 5;
    });
    yPos += 10;

    doc.setFontSize(12);
    doc.setFont(undefined, 'bold');
    doc.text('VERIFIED TIMELINE', margin, yPos);
    yPos += 7;

    doc.setFontSize(9);
    doc.setFont(undefined, 'normal');
    analysis.timeline.forEach((event, i) => {
      if (yPos > 260) {
        doc.addPage();
        yPos = 20;
      }
      
      doc.setFont(undefined, 'bold');
      doc.text(`${i + 1}. ${event.datetime}`, margin, yPos);
      yPos += 5;
      
      doc.setFont(undefined, 'normal');
      const eventLines = doc.splitTextToSize(`Event: ${event.event}`, maxWidth - 5);
      eventLines.forEach(line => {
        doc.text(line, margin + 5, yPos);
        yPos += 5;
      });
      
      doc.text(`Confidence: ${event.confidence.toUpperCase()}`, margin + 5, yPos);
      yPos += 8;
    });

    if (analysis.contradictions.length > 0) {
      yPos += 5;
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text('CONTRADICTIONS DETECTED', margin, yPos);
      yPos += 7;

      doc.setFontSize(9);
      analysis.contradictions.forEach((c, i) => {
        if (yPos > 250) {
          doc.addPage();
          yPos = 20;
        }

        doc.setFont(undefined, 'bold');
        doc.text(`Contradiction ${i + 1}: ${c.severity.toUpperCase()}`, margin, yPos);
        yPos += 5;

        doc.setFont(undefined, 'normal');
        doc.text(`Confidence: ${(c.confidence * 100).toFixed(0)}%`, margin + 5, yPos);
        yPos += 5;

        const claimALines = doc.splitTextToSize(`Claim A: ${c.claim_a.statement}`, maxWidth - 5);
        claimALines.forEach(line => {
          doc.text(line, margin + 5, yPos);
          yPos += 5;
        });

        const claimBLines = doc.splitTextToSize(`Claim B: ${c.claim_b.statement}`, maxWidth - 5);
        claimBLines.forEach(line => {
          doc.text(line, margin + 5, yPos);
          yPos += 5;
        });

        doc.setFont(undefined, 'bold');
        doc.text('Verdict:', margin + 5, yPos);
        yPos += 5;
        doc.setFont(undefined, 'normal');
        const verdictLines = doc.splitTextToSize(c.verdict, maxWidth - 5);
        verdictLines.forEach(line => {
          doc.text(line, margin + 5, yPos);
          yPos += 5;
        });
        yPos += 5;
      });
    }

    if (analysis.summary) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      
      yPos += 5;
      doc.setFontSize(12);
      doc.setFont(undefined, 'bold');
      doc.text('SUMMARY', margin, yPos);
      yPos += 7;

      doc.setFontSize(9);
      doc.setFont(undefined, 'normal');
      const summaryLines = doc.splitTextToSize(analysis.summary, maxWidth);
      summaryLines.forEach(line => {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }
        doc.text(line, margin, yPos);
        yPos += 5;
      });
    }

    doc.save(`verity-analysis-${Date.now()}.pdf`);
  };

  return (
    <div className="flex gap-2">
      <button
        onClick={generatePDFReport}
        className="bg-green-700 text-white px-5 py-3 rounded-lg hover:bg-green-800 transition-colors duration-200 font-medium text-sm"
      >
        Download PDF
      </button>
      <button
        onClick={generateTextReport}
        className="bg-slate-600 text-white px-5 py-3 rounded-lg hover:bg-slate-700 transition-colors duration-200 font-medium text-sm"
      >
        Download TXT
      </button>
    </div>
  );
}