export default function DownloadReport({ analysis }) {
    const generateReport = () => {
      const report = `VERITY FORENSIC ANALYSIS REPORT
  Generated: ${new Date().toLocaleString()}
  
  ========================================
  REASONING PROCESS
  ========================================
  
  ${analysis.thinking}
  
  ========================================
  VERIFIED TIMELINE
  ========================================
  
  ${analysis.timeline.map((event, i) => `
  ${i + 1}. ${event.datetime}
     Event: ${event.event}
     Sources: ${event.sources.join(', ')}
     Confidence: ${event.confidence.toUpperCase()}
     ${event.reasoning ? `Reasoning: ${event.reasoning}` : ''}
  `).join('\n')}
  
  ========================================
  CONTRADICTIONS DETECTED
  ========================================
  
  ${analysis.contradictions.length === 0 ? 'No contradictions found.' : analysis.contradictions.map((c, i) => `
  Contradiction ${i + 1}: ${c.severity.toUpperCase()}
  ID: ${c.id}
  Confidence: ${(c.confidence * 100).toFixed(0)}%
  
  Claim A: ${c.claim_a.statement}
  Source: ${c.claim_a.source}
  Credibility: ${c.claim_a.credibility.toUpperCase()}
  
  Claim B: ${c.claim_b.statement}
  Source: ${c.claim_b.source}
  Credibility: ${c.claim_b.credibility.toUpperCase()}
  
  Analysis: ${c.analysis}
  
  Verdict: ${c.verdict}
  `).join('\n')}
  
  ========================================
  SUMMARY
  ========================================
  
  ${analysis.summary || 'No summary available.'}
  
  ========================================
  END OF REPORT
  ========================================
  
  This report was generated by Verity - Forensic Truth Verification Engine
  Powered by Gemini 3 API
  `;
  
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `verity-analysis-${Date.now()}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    };
  
    return (
      <button
        onClick={generateReport}
        className="bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700 transition flex items-center gap-2"
      >
        <span>📄</span>
        Download Report
      </button>
    );
  }